import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Hero from "@/components/Hero/Hero";
import HomeContent from "@/components/HomeContent/HomeContent";
import Newsletter from "@/components/Newsletter/Newsletter";
import HomeCards from "@/components/HomeCards/HomeCards";
import Modal from "@/components/Modal/Modal";
import { useEffect, useState } from "react";

export async function getStaticProps() {
  const res = await fetch(
    `https://newsapi.org/v2/everything?q=technology&pageSize=3&apiKey=${process.env.NEXT_PUBLIC_NEWS_API}`
  );
  const data = await res.json();

  return {
    props: {
      news: data,
    },
  };
}

export default function Home({ news }) {
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    showModal
      ? (document.body.style.overflow = "hidden")
      : (document.body.style.overflow = "auto");
  }, [showModal]);

  return (
    <>
      <Head>
        <title>Digital Agency</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Modal showModal={showModal} setShowModal={setShowModal} />
      <Header showModal={showModal} setShowModal={setShowModal} />
      <Hero />
      <HomeContent />
      <HomeCards content={news.articles} />
      <Newsletter />
      <Footer />
    </>
  );
}
